easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Consultation
    site_name: ala bala
    translation_domain: 'admin'
    user:
        display_name: true
        display_avatar: false
