easy_admin:
    entities:
        # List the entity class name you want to manage
        - App\Entity\Consultation
    site_name: ala bala
    user:
        display_name: false
        display_avatar: false
